# Generated by Django 6.0.3 on 2026-07-08 22:06
#
# Phase 7: assign an owner to pre-auth data, then enforce user FKs as required.
# - Entry.user existed as null=True/blank=True (Phase 1-6, no auth yet).
# - Comment.user is new in Phase 7.
# Existing rows are assigned to the 'ashwinsh' superuser before the columns
# are made NOT NULL, so no data is lost.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_owner(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Entry = apps.get_model('journal', 'Entry')
    Comment = apps.get_model('journal', 'Comment')

    owner = User.objects.get(username='ashwinsh')
    Entry.objects.filter(user__isnull=True).update(user=owner)
    for comment in Comment.objects.select_related('entry'):
        comment.user_id = comment.entry.user_id
        comment.save(update_fields=['user'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(assign_existing_owner, noop_reverse),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='entries',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
