# Generated by Django 6.0.3 on 2026-07-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_tag_entry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
